# AUTOGENERATED FILE - DO NOT EDIT
from __future__ import annotations as __
import fractions
import functools
from math import inf
import numbers
import typing
import warnings
import msgspec
from . import types
from typing import TypedDict, Union, Optional, List, Any
import enum as Enum


class SpecBase(TypedDict, total=False): ...


class AnalysisFilter(TypedDict, total=False):
    nfft: int
    window: typing.Union[tuple[str, ...], str]
    nfft_out: int | None


class Capture(TypedDict, total=False):
    duration: types.DurationType
    sample_rate: types.SampleRateType
    analysis_bandwidth: types.AnalysisBandwidthType


class _SlowHashSpecBase(TypedDict, total=False): ...


class FilteredCapture(Capture, total=False):
    analysis_filter: AnalysisFilter


class Analysis(TypedDict, total=False): ...


class Measurement(TypedDict, total=False): ...
