"""Reference synthetic waveform generators for tests and examples.

Each generator returns a 2-D array of shape ``(ports, count)`` and is agnostic to
the array namespace (`xp`). All are *windowable*: `start_index` is an absolute
sample index, and a call with `start_index` and `count` returns exactly the slice
``[:, start_index:start_index + count]`` of the whole-capture call with the same
arguments, which is what allows a gapless IQ source to serve one capture in several
reads.

These are the definitions of the waveforms generated by the synthetic sources in
`striqt.sensor.lib.sources.function`.
"""

from __future__ import annotations as __

import typing

from . import util

if typing.TYPE_CHECKING:
    import numpy as np

    from .typing import Array
else:
    np = util.lazy_import('numpy')


def _resolve_count(duration, sample_rate, start_index, count, ports) -> int:
    if ports < 1:
        raise ValueError(f'ports must be at least 1, not {ports}')
    if start_index < 0:
        raise ValueError(f'start_index must be non-negative, not {start_index}')

    if count is None:
        count = round(duration * sample_rate) - start_index

    if count < 0:
        raise ValueError(f'count must be non-negative, not {count}')

    return int(count)


def _sample_indices(start_index, count, xp):
    return xp.arange(start_index, start_index + count, dtype='int64')


def _expand_ports(x: Array, ports: int, xp) -> Array:
    # a broadcast view would be read-only, which is surprising for a waveform
    return xp.broadcast_to(x, (ports, x.shape[-1])).copy()


def _complex_normal_draws(*, ports, size, seed, xp) -> Array:
    """complex64 draws of shape (ports, size) with standard normal components.

    The draws are interleaved port-by-port within each sample, so the first `size`
    samples of every port are a prefix of the stream from ``RandomState(seed)``.
    """
    # RandomState rather than default_rng: it is the generator API that numpy and
    # cupy share
    gen = xp.random.RandomState(seed=seed)
    values = gen.standard_normal(size=2 * size * ports).astype('float32')
    return values.view('complex64').reshape(size, ports).T


def tone(
    duration,
    sample_rate,
    *,
    frequency=0.0,
    ports=1,
    start_index=0,
    count=None,
    xp=np,
    dtype='complex64',
) -> Array:
    """a unit-amplitude complex tone, ``exp(2j*pi*frequency/sample_rate * i)``.

    The sample index `i` is absolute, so the tone has phase 0 at ``i == 0``
    regardless of `start_index`. Mean power is 1, which the power measurements read
    as 0 dBm, since they treat ``|iq|**2`` as mW.

    Args:
        duration: capture duration, in s, used only when `count` is None
        sample_rate: IQ sample rate, in Hz
        frequency: tone frequency, in Hz relative to the center frequency
        ports: number of receive ports, which all get the same samples
        start_index: absolute index of the first returned sample
        count: number of samples, or None for `duration` less `start_index`
        xp: the array namespace to generate with
        dtype: the returned complex dtype

    Returns:
        an array of shape (ports, count)
    """
    count = _resolve_count(duration, sample_rate, start_index, count, ports)
    i = _sample_indices(start_index, count, xp)
    phase_scale = (2j * np.pi * frequency) / sample_rate
    x = xp.exp(phase_scale * i).astype(dtype)
    return _expand_ports(x, ports, xp)


def single_tone(
    duration,
    sample_rate,
    *,
    frequency_offset=0.0,
    snr=None,
    lo_offset=0.0,
    ports=1,
    start_index=0,
    count=None,
    seed=0,
    xp=np,
    dtype='complex64',
) -> Array:
    """a unit-amplitude tone at `frequency_offset`, shifted by an LO offset and
    optionally summed with noise.

    The result is ``tone(frequency=frequency_offset) * tone(frequency=lo_offset)``,
    a tone at ``frequency_offset + lo_offset`` Hz, plus AWGN of total power
    ``10**(-snr/10)`` when `snr` is set. Each port gets the same tone, and
    independent noise.

    Args:
        duration: capture duration, in s, used only when `count` is None
        sample_rate: IQ sample rate, in Hz
        frequency_offset: tone frequency, in Hz relative to the center frequency
        snr: ratio of the tone power to the noise power, in dB, or None for no noise
        lo_offset: additional frequency shift, in Hz, as applied by an LO shift
        ports: number of receive ports
        start_index: absolute index of the first returned sample
        count: number of samples, or None for `duration` less `start_index`
        seed: seed of the noise generator
        xp: the array namespace to generate with
        dtype: the returned complex dtype

    Returns:
        an array of shape (ports, count)
    """
    kws = {'start_index': start_index, 'count': count, 'xp': xp, 'dtype': dtype}
    x = tone(duration, sample_rate, frequency=frequency_offset, ports=ports, **kws)

    if lo_offset:
        x *= tone(duration, sample_rate, frequency=lo_offset, ports=1, **kws)

    if snr is not None:
        x += circular_awgn(
            duration,
            sample_rate,
            power=10 ** (-snr / 10),
            ports=ports,
            seed=seed,
            **kws,
        )

    return x


def circular_awgn(
    duration,
    sample_rate,
    *,
    power=1.0,
    ports=1,
    start_index=0,
    count=None,
    seed=0,
    xp=np,
    dtype='complex64',
) -> Array:
    """circularly-symmetric complex gaussian noise of total power `power`.

    The real and imaginary parts are independent and each has variance
    ``power / 2``, so the mean of ``|iq|**2`` is `power`. Each port is an
    independent draw.

    The draws are interleaved port-by-port within each sample so that the first
    ``start_index + count`` samples of every port are a prefix of the stream from
    ``RandomState(seed)``, which is what makes the result windowable.

    Args:
        duration: capture duration, in s, used only when `count` is None
        sample_rate: IQ sample rate, in Hz, unused except to size `duration`
        power: total power of each port, in linear units
        ports: number of receive ports, which get independent noise
        start_index: absolute index of the first returned sample
        count: number of samples, or None for `duration` less `start_index`
        seed: seed of the noise generator
        xp: the array namespace to generate with
        dtype: the returned complex dtype

    Returns:
        an array of shape (ports, count)
    """
    count = _resolve_count(duration, sample_rate, start_index, count, ports)
    values = _complex_normal_draws(
        ports=ports, size=start_index + count, seed=seed, xp=xp
    )

    # a python float scalar; a numpy scalar would upcast the samples to complex128
    scale = float(np.sqrt(power / 2))
    return (values[:, start_index:] * scale).astype(dtype, copy=False)


def noise(
    duration,
    sample_rate,
    *,
    noise_psd=1e-17,
    ports=1,
    start_index=0,
    count=None,
    seed=0,
    xp=np,
    dtype='complex64',
) -> Array:
    """additive white gaussian noise of the specified power spectral density.

    This is `circular_awgn` at a total power of ``noise_psd * sample_rate``, so each
    of the real and imaginary components is gaussian with standard deviation
    ``sqrt(noise_psd * sample_rate / 2)``. Each port is an independent draw.

    Args:
        duration: capture duration, in s, used only when `count` is None
        sample_rate: IQ sample rate, in Hz
        noise_psd: noise power spectral density, in W/Hz
        ports: number of receive ports, which get independent noise
        start_index: absolute index of the first returned sample
        count: number of samples, or None for `duration` less `start_index`
        seed: seed of the noise generator
        xp: the array namespace to generate with
        dtype: the returned complex dtype

    Returns:
        an array of shape (ports, count)
    """
    return circular_awgn(
        duration,
        sample_rate,
        power=noise_psd * sample_rate,
        ports=ports,
        start_index=start_index,
        count=count,
        seed=seed,
        xp=xp,
        dtype=dtype,
    )


def sawtooth(
    duration,
    sample_rate,
    *,
    period=0.01,
    power=0.0,
    ports=1,
    start_index=0,
    count=None,
    xp=np,
    dtype='complex64',
) -> Array:
    """a real-valued sawtooth ramp, ``(t % period) * 10**(power/20) / period``.

    Here ``t = i / sample_rate`` at absolute sample index `i`, so the ramp starts
    at 0 and resets every `period` s. Its peak amplitude is ``10**(power/20)``, and
    the imaginary part is 0. Each port gets the same samples.

    Args:
        duration: capture duration, in s, used only when `count` is None
        sample_rate: IQ sample rate, in Hz
        period: duration of one ramp, in s
        power: peak amplitude of the ramp expressed as a power, in dB
        ports: number of receive ports
        start_index: absolute index of the first returned sample
        count: number of samples, or None for `duration` less `start_index`
        xp: the array namespace to generate with
        dtype: the returned complex dtype

    Returns:
        an array of shape (ports, count)
    """
    if period <= 0:
        raise ValueError(f'period must be positive, not {period}')

    count = _resolve_count(duration, sample_rate, start_index, count, ports)
    t = _sample_indices(start_index, count, xp) / sample_rate
    amplitude = 10 ** (power / 20)
    x = ((t % period) * (amplitude / period)).astype(dtype)
    return _expand_ports(x, ports, xp)


def dirac_delta(
    duration,
    sample_rate,
    *,
    time=0.0,
    power=0.0,
    ports=1,
    start_index=0,
    count=None,
    xp=np,
    dtype='complex64',
) -> Array:
    """a single impulse of amplitude ``10**(power/20)`` in a field of zeros.

    The impulse sits at absolute sample index ``round(time * sample_rate)``, and the
    result is all zeros when that index falls outside the returned window. Each port
    gets the same samples.

    Args:
        duration: capture duration, in s, used only when `count` is None
        sample_rate: IQ sample rate, in Hz
        time: time of the impulse, in s from the start of the capture
        power: impulse amplitude expressed as a power, in dB
        ports: number of receive ports
        start_index: absolute index of the first returned sample
        count: number of samples, or None for `duration` less `start_index`
        xp: the array namespace to generate with
        dtype: the returned complex dtype

    Returns:
        an array of shape (ports, count)
    """
    count = _resolve_count(duration, sample_rate, start_index, count, ports)
    x = xp.zeros(count, dtype=dtype)
    index = round(time * sample_rate) - start_index

    if 0 <= index < count:
        x[index] = 10 ** (power / 20)

    return _expand_ports(x, ports, xp)
