[workspace]
authors = ["Dan Kuester <daniel.kuester@nist.gov>"]
channels = ["conda-forge"]
name = "striqt"
platforms = ["osx-arm64","linux-aarch64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
warmup = "_warmup_striqt"

[dependencies]

# general development
python = ">=3.9.0"
pip = "*"

# I/O and validation
msgspec = "~=0.19"

# numerical
array-api-compat = "*"
cython = "*"
dask = "*"
numba = ">=0.56"
numcodecs = "*"
numexpr = ">=2.8"
numpy = ">=1.21"
netcdf4 = "*"
pandas = ">=1.5"
scipy = ">=1.9"
xarray = ">=2024.3"
zarr = ">=2.18.2"

# plotting
mscorefonts = "*"
matplotlib-base = ">=3.7"

# hardware 
soapysdr = ">=0.8.1"

[pypi-dependencies]
striqt = {path = ".", editable = true, extras = ["dev"]}

[feature.py39.dependencies]
python = "~=3.9.0"

[feature.py314.dependencies]
python = "~=3.14.0"

[feature.test.dependencies]
nptdms = "*"
SoapySDR = "*"

[feature.test.pypi-dependencies]
striqt = {path = ".", editable = true, extras = ["dev", "test"]}

[feature.doc.pypi-dependencies]
striqt = {path = ".", editable = true, extras = ["dev", "doc"]}

[feature.cupy]
platforms = ["linux-aarch64", "linux-64", "win-64"]

[feature.cupy.dependencies]
cupy = ">=12.2"

[environments]
default = ["py39"]
cupy = ["cupy"]
test = ["test"]
py39 = ["py39"]
py314 = ["py314"]
test39 = ["test","py39"]
test314 = ["test","py314"]
doc = ["doc", "py314"]
