# the base environment that supports CPU computations (no GPU or SDRs)

name: flex-spectrum-sensor

channels:
  - conda-forge

dependencies:
  # development
  - python
  - pip
  - jupyter
  - ruff
  - toml
  - ruamel.yaml

  # hard-coded on behalf of pip for iqwaveform
  - pandas
  - scipy>=1.13,<2
  - numpy>=1.21,<3
  - matplotlib-base~=3.7
  - numexpr~=2.8
  - array-api-compat
  - methodtools
  - numba

  # for device wrappers and remote control
  - labbench>=0.42.0,<1
  - rpyc~=5.3

  # data management (including zarr and data chunking in xarray)
  - xarray>=2024.3
  - zarr>=2.18,<4
  - dask
  - msgspec~=0.18
  - frozendict

  # for documentation and plotting
  - schemdraw
  - mscorefonts

  - pip:
      - iqwaveform @ git+https://github.com/usnistgov/iqwaveform
      - xarray_dataclasses @ git+https://github.com/dgkuester/xarray-dataclasses@lazy-imports

      # allows imports from the src/ directory in this repo
      - -e ..
