# the base environment that supports CPU computations (no GPU or SDRs)

name: flex-spectrum-sensor

channels:
  - conda-forge

dependencies:
  # python3.9 is the most recent supported by the Air-T Jetson stack
  - python=3.9
  - pip
  - jupyter
  - ruff

  # hard-coded on behalf of pip for iqwaveform
  - pandas>=1.5,<2
  - scipy>=1.9.2
  - seaborn>=0.12
  - numpy>=1.21,<2
  - matplotlib-base>=3.7
  - numexpr>=2.7
  - scikit-learn>=1.1,<2.0
  - pyppeteer
  - ipympl
  - numexpr>=2.8.4
  - humanfriendly
  - array-api-compat
  - methodtools


  # for SoapySDR device wrappers and remote control
  - labbench>=0.42.0,<1
  - rpyc>=5.3,<6
  - soapysdr

  # data management (including zarr and data chunking in xarray)
  - xarray
  - zarr>=2.18,<3
  - dask
  - msgspec

  # git repository introspection support for metadata
  - dulwich

  # for environment.yml autogeneration
  - ruamel.yaml

  # for documentation
  - schemdraw

  - pip:
      - iqwaveform @ git+https://github.com/usnistgov/iqwaveform
      - xarray_dataclasses @ git+https://github.com/dgkuester/xarray-dataclasses@lazy-imports

      # allows imports from the src/ directory in this repo
      - -e ..
